"""Read and write configuration CSVs in the sectioned layout used by the GUI and tools.

A configuration CSV has three sections, each introduced by a line starting
with ``*`` and the section name. Lines containing ``#`` are comments.
"""

import io

import pandas as pd

PAD = "," * 50


def read_config_csv(path: str) -> dict:
    """Parse the sectioned CSV into ``{section_name: DataFrame}`` (all strings)."""
    with open(path, "r", encoding="utf-8") as f:
        raw = f.readlines()

    no_comments = [l for l in raw if "#" not in l]
    titles = [
        (l.replace(",", " ").strip(" *\r\n"), i)
        for i, l in enumerate(no_comments)
        if l.startswith("*")
    ]

    sections = {}
    for i, (name, start) in enumerate(titles):
        end = titles[i + 1][1] if i + 1 < len(titles) else len(no_comments)
        lines = [l.rstrip().rstrip(",") for l in no_comments[start + 1 : end]]
        text = "\n".join(lines)
        if not text.strip():
            continue
        df = pd.read_csv(
            io.StringIO(text), delimiter=",", header=0, engine="python", dtype=str
        ).dropna(how="all")
        df = df.loc[:, ~df.columns.str.contains("^Unnamed")]
        df.columns = df.columns.str.strip()
        sections[name] = df
    return sections


def write_config_csv(
    path: str,
    df_global: pd.DataFrame,
    df_banks: pd.DataFrame,
    df_buttons: pd.DataFrame,
    note: str = "Generated by GUI",
    df_long_press: pd.DataFrame = None,
    df_expression: pd.DataFrame = None,
    df_bank_enter: pd.DataFrame = None,
) -> None:
    with open(path, "w", newline="", encoding="utf-8") as f:
        f.write("# Notes" + PAD + "\n")
        f.write(f"# {note}" + PAD + "\n")
        f.write("#" + PAD + "\n")

        f.write("* Global_Settings" + PAD + "\n")
        df_global.to_csv(f, index=False)
        f.write(PAD + "\n")

        f.write("* Bank_Naming" + PAD + "\n")
        df_banks.to_csv(f, index=False)
        f.write(PAD + "\n")

        f.write("* Button_Settings" + PAD + "\n")
        df_buttons.to_csv(f, index=False)

        if df_long_press is not None:
            f.write(PAD + "\n")
            f.write("* LongPress_Settings" + PAD + "\n")
            df_long_press.to_csv(f, index=False)

        if df_expression is not None:
            f.write(PAD + "\n")
            f.write("* Expression_Settings" + PAD + "\n")
            df_expression.to_csv(f, index=False)

        if df_bank_enter is not None:
            f.write(PAD + "\n")
            f.write("* BankEnter_Settings" + PAD + "\n")
            df_bank_enter.to_csv(f, index=False)
