"""What the Meris X templates share: Enzo X, LVX and MercuryX.

The three have the same MIDI map for what a footswitch does, "MIDI CC TABLE"
and "MIDI PC TABLE" in their manuals (v1.5.1, MercuryX v1.5): Program Change
1-99 loads a preset, 100-102 the three favorites, and CC 14, 117 and 118
bypass, open the tuner and trigger the Hold Modifier. The Enzo X and the LVX
also take a tap on CC 99, and the LVX's looper is on CC 100-103.
"""
from lib.templateMaker import NO_SEND, full_range_pedals, global_settings, write_template
from make_demo_config import Demo

CHANNEL = "1"           # the pedal's MIDI CHANNEL, in its Globals

CC_EXP = "4"            # Expression Pedal
CC_BYPASS = "14"        # 0-63 bypass, 64-127 enable
CC_TAP = "99"           # press = 127
CC_TUNER = "117"        # press = 127 opens and closes it
CC_HOLD = "118"         # press = 127, release = 0
# The LVX's looper, press = 127
CC_LOOP_REC = "100"     # record / overdub
CC_LOOP_PLAY = "101"    # play / stop
CC_LOOP_FX1 = "102"
CC_LOOP_FX2 = "103"

PRESETS = 99
FAVORITES = 3           # PC 100-102
PRESET_BUTTONS = ("1", "2", "3", "A", "B", "C")     # two of the Meris's banks of three
PRESET_BANKS = 17       # banks 0-16: presets 1-99, then the favorites
CTL_BANK = 31
ANY = "127"


def programs():
    """(label, program) of each preset button in order: P01-P99, FAV1-FAV3."""
    return ([(f"P{n:02d}", n) for n in range(1, PRESETS + 1)]
            + [(f"FAV{n}", PRESETS + n) for n in range(1, FAVORITES + 1)])


def build(model, cc_mix, tap=True, looper=False):
    d = Demo()
    names = {}
    presets = programs()

    for bank in range(PRESET_BANKS):
        chunk = presets[bank * len(PRESET_BUTTONS):(bank + 1) * len(PRESET_BUTTONS)]
        names[bank] = (chunk[0][0], model)
        for btn, (label, program) in zip(PRESET_BUTTONS, chunk):
            d.pc(bank, btn, label, str(program), ch=CHANNEL)
        # Lit while bypassed; starts dark, taking the pedal to be enabled
        d.cc(bank, "4", "BYP", CC_BYPASS, on="0", off="127", toggle="Y", ch=CHANNEL)
        d.long_press(bank, "4", CommandType="CC",
                     **{"Channel_(PC/CC/Note/PB)": CHANNEL, "Number_(PC/CC/Note)": CC_TUNER,
                        "OnValue_(CC/PB)": ANY, "OffValue_(CC)": NO_SEND, "Toggle_(CC/PB/Note)": "N"})
        d.long_label(bank, "4", "TUNE")
        if tap:
            # Sent on the press only; a second message would count as a tap
            d.cc(bank, "D", "TAP", CC_TAP, on=ANY, off=NO_SEND, ch=CHANNEL)
        else:
            d.cc(bank, "D", "HOLD", CC_HOLD, ch=CHANNEL)

    names[CTL_BANK] = ("CTL", model)
    d.cc(CTL_BANK, "1", "BYP", CC_BYPASS, on="0", off="127", toggle="Y", ch=CHANNEL)
    # Held while the button is, then released, as the manual asks
    d.cc(CTL_BANK, "2", "HOLD", CC_HOLD, ch=CHANNEL)
    d.cc(CTL_BANK, "3", "TUNE", CC_TUNER, on=ANY, off=NO_SEND, ch=CHANNEL)
    if looper:
        for btn, label, number in (("A", "REC", CC_LOOP_REC), ("B", "PLAY", CC_LOOP_PLAY),
                                   ("C", "FX1", CC_LOOP_FX1), ("4", "FX2", CC_LOOP_FX2)):
            d.cc(CTL_BANK, btn, label, number, on=ANY, off=NO_SEND, ch=CHANNEL)
    if tap:
        d.cc(CTL_BANK, "D", "TAP", CC_TAP, on=ANY, off=NO_SEND, ch=CHANNEL)

    full_range_pedals(d)
    return d, names


def write(out, model, cc_mix, script, **options):
    d, names = build(model, cc_mix, **options)
    return write_template(out, d, names, global_settings(model, CHANNEL, CC_EXP, cc_mix),
                          f"Meris {model} template, generated by {script}")
