#! env python3
# -*- coding: utf-8 -*-
"""Generate the Strymon Volante template, python/templates/Volante.csv.

The Volante has a fixed MIDI map, "MIDI CC numbers" in its manual (rev E),
so nothing has to be assigned on it: only its MIDI channel, green for
channel 1 by default.

    python3 python/make_volante_template.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from lib.templateMaker import NO_SEND, full_range_pedals, global_settings, write_template  # noqa: E402
from make_demo_config import Demo  # noqa: E402

OUT = os.path.join(HERE, "templates", "Volante.csv")

CHANNEL = "1"           # the Volante's MIDI channel

# The Volante's MIDI map
CC_ECHO_LEVEL = "12"
CC_HEADS = ("21", "22", "23", "24")     # playback heads 1-4: 0 off, 1-127 on
CC_SOS = "41"           # 0 normal, 1-127 SOS looper mode
CC_PAUSE = "43"         # pause with the ramp: 0 unpause, 1-127 pause
CC_REVERSE = "44"       # 0 normal, 1-127 reverse
CC_HOLD = "45"          # infinite hold, with oscillation: 0 release, 1-127 hold
CC_SOS_REC = "49"       # SOS record / splice / clear, any value
CC_SOS_EXIT = "50"      # exit the SOS looper, any value
CC_ECHO = "78"          # 0 off, 127 on
CC_REVERB = "79"
CC_TAP = "93"           # Remote Tap, any value
CC_EXP = "100"          # Expression Pedal
CC_BYPASS = "102"       # 0 bypass, 1-127 on

PRESET_BANKS = 30       # banks 0-29 load presets 0-29; 0-7 are the eight on its buttons
SOS_BANK = 30
HEADS_BANK = 31
ANY = "127"


def switch(d, bank, btn, label, number):
    d.cc(bank, btn, label, number, toggle="Y", ch=CHANNEL)


def tap(d, bank):
    # Tap sends only on the press; a second message would count as a tap
    d.cc(bank, "D", "TAP", CC_TAP, on=ANY, off=NO_SEND, ch=CHANNEL)


def build():
    d = Demo()
    names = {}

    for bank in range(PRESET_BANKS):
        names[bank] = (f"P{bank:03d}", "Volante")
        d.on_enter(bank, CommandType="PC",
                   **{"Channel_(PC/CC/Note/PB)": CHANNEL, "Number_(PC/CC/Note)": str(bank)})
        # Lit while bypassed: a preset loads on
        d.cc(bank, "1", "BYP", CC_BYPASS, on="0", off="127", toggle="Y", ch=CHANNEL)
        switch(d, bank, "2", "REV", CC_REVERSE)
        switch(d, bank, "3", "PAUS", CC_PAUSE)
        # Held while the button is
        d.cc(bank, "4", "HOLD", CC_HOLD, ch=CHANNEL)
        tap(d, bank)

    names[SOS_BANK] = ("SOS", "looper")
    switch(d, SOS_BANK, "1", "SOS", CC_SOS)
    d.cc(SOS_BANK, "2", "REC", CC_SOS_REC, on=ANY, off=NO_SEND, ch=CHANNEL)
    d.cc(SOS_BANK, "3", "EXIT", CC_SOS_EXIT, on=ANY, off=NO_SEND, ch=CHANNEL)
    switch(d, SOS_BANK, "4", "REV", CC_REVERSE)
    switch(d, SOS_BANK, "A", "PAUS", CC_PAUSE)
    tap(d, SOS_BANK)

    names[HEADS_BANK] = ("HEAD", "heads")
    for btn, number, n in zip(("1", "2", "3", "4"), CC_HEADS, range(1, 5)):
        switch(d, HEADS_BANK, btn, f"HD{n}", number)
    switch(d, HEADS_BANK, "A", "ECHO", CC_ECHO)
    switch(d, HEADS_BANK, "B", "VERB", CC_REVERB)
    tap(d, HEADS_BANK)

    full_range_pedals(d)
    return d, names


def main() -> int:
    d, names = build()
    return write_template(OUT, d, names, global_settings("Volante", CHANNEL, CC_EXP, CC_ECHO_LEVEL),
                          "Strymon Volante template, generated by make_volante_template.py")


if __name__ == "__main__":
    sys.exit(main())
