#! env python3
# -*- coding: utf-8 -*-
"""Generate the Strymon BigSky template, python/templates/BigSky.csv.

The BigSky has a fixed MIDI map, "MIDI CC numbers" in its manual (rev D),
so nothing has to be assigned on it: only its MIDI channel, and MIDI
Continuous Controllers and MIDI Patch Change turned on, in its Globals.

    python3 python/make_bigsky_template.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from lib.templateMaker import NO_SEND, full_range_pedals, global_settings, write_template  # noqa: E402
from make_demo_config import Demo  # noqa: E402

OUT = os.path.join(HERE, "templates", "BigSky.csv")

CHANNEL = "1"           # the BigSky's MIDI Channel, in its Globals

# The BigSky's MIDI map
CC_MIX = "15"
CC_FS_A = "80"          # the A, B and C footswitches: 0 down, 127 up
CC_FS_B = "82"
CC_FS_C = "81"
CC_TAP = "93"           # Remote TAP, any value
CC_HOLD = "97"          # Press/Hold switch, infinite or freeze: 0 off, 127 on
CC_EXP = "100"          # Expression Pedal
CC_BYPASS = "102"       # 0 bypass, 127 engage

PRESET_BANKS = 31       # banks 0-30 load presets 00A-10A
FS_BANK = 31
ANY = "127"


def preset_name(program):
    """The BigSky's own name for a preset: 00A, 00B, 00C, 01A..."""
    return f"{program // 3:02d}{'ABC'[program % 3]}"


def build():
    d = Demo()
    names = {}

    for bank in range(PRESET_BANKS):
        names[bank] = (preset_name(bank), "BigSky")
        d.on_enter(bank, CommandType="PC",
                   **{"Channel_(PC/CC/Note/PB)": CHANNEL, "Number_(PC/CC/Note)": str(bank)})
        # Lit while bypassed: a preset loads engaged
        d.cc(bank, "1", "BYP", CC_BYPASS, on="0", off="127", toggle="Y", ch=CHANNEL)
        # Held while the button is, as the BigSky's own hold
        d.cc(bank, "2", "HOLD", CC_HOLD, ch=CHANNEL)
        # Latched: one press on, the next off
        d.cc(bank, "3", "LTCH", CC_HOLD, toggle="Y", ch=CHANNEL)
        # Tap sends only on the press; a second message would count as a tap
        d.cc(bank, "D", "TAP", CC_TAP, on=ANY, off=NO_SEND, ch=CHANNEL)

    names[FS_BANK] = ("FS", "switches")
    # As the BigSky's own footswitches: 0 on the press, 127 on the release
    for btn, label, number in (("A", "FS-A", CC_FS_A), ("B", "FS-B", CC_FS_B), ("C", "FS-C", CC_FS_C)):
        d.cc(FS_BANK, btn, label, number, on="0", off="127", ch=CHANNEL)
    d.cc(FS_BANK, "1", "BYP", CC_BYPASS, on="0", off="127", toggle="Y", ch=CHANNEL)
    d.cc(FS_BANK, "2", "HOLD", CC_HOLD, ch=CHANNEL)
    d.cc(FS_BANK, "D", "TAP", CC_TAP, on=ANY, off=NO_SEND, ch=CHANNEL)

    full_range_pedals(d)
    return d, names


def main() -> int:
    d, names = build()
    return write_template(OUT, d, names, global_settings("BigSky", CHANNEL, CC_EXP, CC_MIX),
                          "Strymon BigSky template, generated by make_bigsky_template.py")


if __name__ == "__main__":
    sys.exit(main())
