#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the Ableton Live template, python/templates/Ableton_Live.csv.

Live answers no Program Change, so this one is two banks: the Session View
and the transport on Live's own keyboard shortcuts, sent by the pedal as a
USB keyboard to the Live window in front, and eight FX buttons whose CCs,
with tap tempo's, are mapped once in MIDI Map mode (see the CC_* constants
and the manual). A setlist keeps Bank Up / Down on the two.

    python3 python/make_ableton_live_template.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from lib.templateMaker import full_range_pedals, global_settings, write_template  # noqa: E402
from make_demo_config import Demo  # noqa: E402

OUT = os.path.join(HERE, "templates", "Ableton_Live.csv")

CHANNEL = "1"
SHIFT = "2"             # the Key command's modifier
# Live's shortcuts
KEYS = (("1", "SCN-", "", "up"),        # the scene above
        ("2", "SCN+", "", "down"),      # the scene below
        ("3", "LNCH", "", "enter"),     # launches the scene selected
        ("4", "METR", "", "o"),         # the metronome, Live 12
        ("A", "PLAY", "", "space"),     # play from the start marker / stop
        ("B", "CONT", SHIFT, "space"),  # continue from where it stopped
        ("C", "REC", "", "f9"))         # record
# MIDI Map mode: 127 on the press, 0 on the release for tap, 127 on and
# 0 off for the FX
CC_TAP = "20"
CC_FX = ("21", "22", "23", "24", "25", "26", "27", "28")
CC_EXP1 = "11"
CC_EXP2 = "1"

LIVE_BANK = 0
FX_BANK = 1


def build():
    d = Demo()
    names = {LIVE_BANK: ("LIVE", "session"), FX_BANK: ("FX", "mapped")}
    for btn, label, mods, key in KEYS:
        d.key(LIVE_BANK, btn, label, mods, key)
    d.cc(LIVE_BANK, "D", "TAP", CC_TAP, ch=CHANNEL)
    for btn, number, n in zip(("1", "2", "3", "4", "A", "B", "C", "D"), CC_FX, range(1, 9)):
        d.cc(FX_BANK, btn, f"FX{n}", number, toggle="Y", ch=CHANNEL)
    full_range_pedals(d)
    return d, names


def main() -> int:
    d, names = build()
    settings = global_settings("Ableton Live", CHANNEL, CC_EXP1, CC_EXP2, extra=(("Setlist_Mode", "Y"),))
    return write_template(OUT, d, names, settings,
                          "Ableton Live template, generated by make_ableton_live_template.py",
                          setlist=[LIVE_BANK, FX_BANK])


if __name__ == "__main__":
    sys.exit(main())
