#! env python3
# -*- coding: utf-8 -*-
"""Generate the Eventide H90 template, python/templates/H90.csv.

The H90 has no MIDI CC mapped out of the box ("The H90 has no default MIDI
CC or external controller mappings", its manual, appendix C), so the numbers
below are the ones the template sends and have to be mapped to the matching
Global Controls on the H90, under System > MIDI > Global Control (see the
CC_* constants and the manual). Programs need nothing: a Program Change
loads one from the current Playlist.

    python3 python/make_h90_template.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from lib.templateMaker import NO_SEND, full_range_pedals, global_settings, write_template  # noqa: E402
from make_demo_config import Demo  # noqa: E402

OUT = os.path.join(HERE, "templates", "H90.csv")

CHANNEL = "1"           # the H90's MIDI channel, System > MIDI

# System > MIDI > Global Control: each of these toggles on a value of 64 or
# more, so every press sends 127 and a release nothing
CC_P_BYPASS = "20"      # P Act/Byp, the whole Program
CC_A_BYPASS = "21"      # A Act/Byp
CC_B_BYPASS = "22"      # B Act/Byp
CC_HS = ("23", "24", "25")  # HS1, HS2, HS3
CC_TUNER = "26"         # Tuner
CC_TAP = "27"           # Tap Tempo
CC_PERFORM = ("40", "41", "42", "43", "44", "45")  # PERFORM 1-6
# The expression pedals, mapped the same way as knobs
CC_HOTKNOB = "16"       # P HotKnob
CC_OUT_GAIN = "17"      # P Out Gain

PRESET_BANKS = 31       # banks 0-30 load Programs 1-31 of the Playlist
PERFORM_BANK = 31
PRESS = "127"


def switch(d, bank, btn, label, number):
    # Each 127 toggles it on the H90, so both presses send one; the LED is
    # the pedal's guess, lit on every other press
    d.cc(bank, btn, label, number, on=PRESS, off=PRESS, toggle="Y", ch=CHANNEL)


def tuner_and_tap(d, bank):
    switch(d, bank, "C", "TUNR", CC_TUNER)
    # Tap sends only on the press; a second message on the release would
    # count as another tap
    d.cc(bank, "D", "TAP", CC_TAP, off=NO_SEND, ch=CHANNEL)


def build():
    d = Demo()
    names = {}

    for bank in range(PRESET_BANKS):
        # PC 0 on the wire is the H90's PC 1, Program 1
        names[bank] = (f"P{bank + 1:03d}", "H90 prog")
        d.on_enter(bank, CommandType="PC",
                   **{"Channel_(PC/CC/Note/PB)": CHANNEL, "Number_(PC/CC/Note)": str(bank)})
        switch(d, bank, "1", "A", CC_A_BYPASS)
        switch(d, bank, "2", "B", CC_B_BYPASS)
        switch(d, bank, "3", "PGM", CC_P_BYPASS)
        for btn, number, n in zip(("4", "A", "B"), CC_HS, (1, 2, 3)):
            switch(d, bank, btn, f"HS{n}", number)
        tuner_and_tap(d, bank)

    names[PERFORM_BANK] = ("PERF", "perform")
    for btn, number, n in zip(("1", "2", "3", "4", "A", "B"), CC_PERFORM, range(1, 7)):
        switch(d, PERFORM_BANK, btn, f"PRF{n}", number)
    tuner_and_tap(d, PERFORM_BANK)

    full_range_pedals(d)
    return d, names


def main() -> int:
    d, names = build()
    return write_template(OUT, d, names, global_settings("H90", CHANNEL, CC_HOTKNOB, CC_OUT_GAIN),
                          "Eventide H90 template, generated by make_h90_template.py")


if __name__ == "__main__":
    sys.exit(main())
