#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the Strymon TimeLine template, python/templates/TimeLine.csv.

The TimeLine has a fixed MIDI map, "MIDI CC numbers" in its manual (rev H),
so nothing has to be assigned on it: only its MIDI channel, and MIDI
Continuous Controllers and MIDI Patch Change turned on, in its Globals.

    python3 python/make_timeline_template.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from lib.templateMaker import NO_SEND, full_range_pedals, global_settings, write_template  # noqa: E402
from make_demo_config import Demo  # noqa: E402

OUT = os.path.join(HERE, "templates", "TimeLine.csv")

CHANNEL = "1"           # the TimeLine's MIDI Channel, in its Globals

# The TimeLine's MIDI map
CC_MIX = "14"
CC_FS_A = "80"          # the A and B footswitches: 0 down, 127 up
CC_FS_B = "82"
CC_TAP = "93"           # Remote TAP, any value
CC_INFINITE = "97"      # 0 off, 127 on
CC_EXP = "100"          # Expression Pedal
CC_BYPASS = "102"       # 0 bypass, 127 engage
# The looper: any value
CC_STOP = "85"
CC_PLAY = "86"
CC_REC = "87"
CC_UNDO = "89"
CC_REDO = "90"
CC_REV = "94"           # reverse, a toggle
CC_HALF = "95"          # full / half speed, a toggle
CC_PRE_POST = "96"      # a toggle

PRESET_BANKS = 30       # banks 0-29 load presets 00A-14B
LOOP_BANK = 30
FS_BANK = 31
ANY = "127"


def preset_name(program):
    """The TimeLine's own name for a preset: 00A, 00B, 01A..."""
    return f"{program // 2:02d}{'AB'[program % 2]}"


def bypass_infinite_tap(d, bank, byp="1", inf="2"):
    # Lit while bypassed: a preset loads engaged
    d.cc(bank, byp, "BYP", CC_BYPASS, on="0", off="127", toggle="Y", ch=CHANNEL)
    d.cc(bank, inf, "INF", CC_INFINITE, toggle="Y", ch=CHANNEL)
    # Tap sends only on the press; a second message would count as a tap
    d.cc(bank, "D", "TAP", CC_TAP, on=ANY, off=NO_SEND, ch=CHANNEL)


def trigger(d, bank, btn, label, number):
    d.cc(bank, btn, label, number, on=ANY, off=NO_SEND, ch=CHANNEL)


def looper_switch(d, bank, btn, label, number):
    # Each message flips it on the TimeLine, so both presses send one
    d.cc(bank, btn, label, number, on=ANY, off=ANY, toggle="Y", ch=CHANNEL)


def build():
    d = Demo()
    names = {}

    for bank in range(PRESET_BANKS):
        names[bank] = (preset_name(bank), "TimeLine")
        d.on_enter(bank, CommandType="PC",
                   **{"Channel_(PC/CC/Note/PB)": CHANNEL, "Number_(PC/CC/Note)": str(bank)})
        bypass_infinite_tap(d, bank)

    names[LOOP_BANK] = ("LOOP", "looper")
    trigger(d, LOOP_BANK, "1", "REC", CC_REC)
    trigger(d, LOOP_BANK, "2", "PLAY", CC_PLAY)
    trigger(d, LOOP_BANK, "3", "STOP", CC_STOP)
    trigger(d, LOOP_BANK, "4", "UNDO", CC_UNDO)
    trigger(d, LOOP_BANK, "A", "REDO", CC_REDO)
    looper_switch(d, LOOP_BANK, "B", "REV", CC_REV)
    looper_switch(d, LOOP_BANK, "C", "HALF", CC_HALF)
    trigger(d, LOOP_BANK, "D", "TAP", CC_TAP)

    names[FS_BANK] = ("FS", "switches")
    # As the TimeLine's own footswitches: 0 on the press, 127 on the release
    d.cc(FS_BANK, "A", "FS-A", CC_FS_A, on="0", off="127", ch=CHANNEL)
    d.cc(FS_BANK, "B", "FS-B", CC_FS_B, on="0", off="127", ch=CHANNEL)
    looper_switch(d, FS_BANK, "C", "PRE", CC_PRE_POST)
    bypass_infinite_tap(d, FS_BANK)

    full_range_pedals(d)
    return d, names


def main() -> int:
    d, names = build()
    return write_template(OUT, d, names, global_settings("TimeLine", CHANNEL, CC_EXP, CC_MIX),
                          "Strymon TimeLine template, generated by make_timeline_template.py")


if __name__ == "__main__":
    sys.exit(main())
