#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the Hotone Ampero II template, python/templates/Ampero_II.csv.

The Ampero II has a fixed MIDI map, its "MIDI Control Information List"
(firmware V1.0.2), so nothing has to be assigned on it: out of the box it
listens on every channel, Omni, from the MIDI IN socket and USB.

    python3 python/make_ampero_ii_template.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from lib.templateMaker import NO_SEND, full_range_pedals, global_settings, write_template  # noqa: E402
from make_demo_config import Demo  # noqa: E402

OUT = os.path.join(HERE, "templates", "Ampero_II.csv")

CHANNEL = "1"           # any channel does while the Ampero II is on Omni

# The Ampero II's MIDI map; the on/off ones: 0-63 off, 64-127 on
CC_VOLUME = "7"         # Patch Volume, 0-100
CC_EXP = "11"           # Expression Pedal (EXP 3)
CC_SCENE = "25"         # 1-4, scenes 1-4
CC_DRUM_MENU = "36"
CC_DRUM_PLAY = "37"     # 0-63 stop, 64-127 play
CC_TUNER = "60"
CC_LOOPER = "62"        # the looper's menu
CC_LOOP_REC = "63"      # record / overdub
CC_LOOP_PLAY = "64"     # 0-63 stop, 64-127 play
CC_LOOP_SPEED = "65"    # 0-63 half speed, 64-127 normal
CC_LOOP_DIR = "66"      # 0-63 reverse, 64-127 normal
CC_LOOP_UNDO = "67"     # undo / redo
CC_LOOP_CLEAR = "68"
CC_TAP = "76"
CC_BYPASS = "78"        # 0 analog bypass, 1 DSP bypass, 2 engage
CC_FS = ("79", "80", "81", "82")    # the effect slots on FS 1-4

PRESET_BANKS = 30       # banks 0-29 load patches 01-1 to 08-2
LOOP_BANK = 30
FS_BANK = 31
PRESS = "127"


def patch_name(program):
    """The Ampero II's own name for a patch: 01-1 ... 01-4, 02-1..."""
    return f"{program // 4 + 1:02d}-{program % 4 + 1}"


def switch(d, bank, btn, label, number):
    d.cc(bank, btn, label, number, toggle="Y", ch=CHANNEL)


def tuner_and_tap(d, bank):
    switch(d, bank, "C", "TUNR", CC_TUNER)
    # Tap sends only on the press; a second message would count as a tap
    d.cc(bank, "D", "TAP", CC_TAP, off=NO_SEND, ch=CHANNEL)


def press(d, bank, btn, label, number):
    d.cc(bank, btn, label, number, off=NO_SEND, ch=CHANNEL)


def build():
    d = Demo()
    names = {}

    for bank in range(PRESET_BANKS):
        names[bank] = (patch_name(bank), "Ampero")
        d.on_enter(bank, CommandType="PC",
                   **{"Channel_(PC/CC/Note/PB)": CHANNEL, "Number_(PC/CC/Note)": str(bank)})
        for btn, scene in (("1", 1), ("2", 2), ("3", 3), ("4", 4)):
            # An exclusive group, so the LED and the display show the scene
            # last picked; switching it off sends nothing
            d.cc(bank, btn, f"SCN{scene}", CC_SCENE, on=str(scene), off=NO_SEND, toggle="Y", ch=CHANNEL)
            d.group(bank, btn, 1)
        # The effect slots on the Ampero II's FS1 and FS2: 127, then 0
        switch(d, bank, "A", "FS1", CC_FS[0])
        switch(d, bank, "B", "FS2", CC_FS[1])
        tuner_and_tap(d, bank)

    names[LOOP_BANK] = ("LOOP", "looper")
    switch(d, LOOP_BANK, "1", "LOOP", CC_LOOPER)
    press(d, LOOP_BANK, "2", "REC", CC_LOOP_REC)
    switch(d, LOOP_BANK, "3", "PLAY", CC_LOOP_PLAY)
    press(d, LOOP_BANK, "4", "UNDO", CC_LOOP_UNDO)
    press(d, LOOP_BANK, "A", "CLR", CC_LOOP_CLEAR)
    # Lit while half speed, and while reversed
    d.cc(LOOP_BANK, "B", "HALF", CC_LOOP_SPEED, on="0", off=PRESS, toggle="Y", ch=CHANNEL)
    d.cc(LOOP_BANK, "C", "REV", CC_LOOP_DIR, on="0", off=PRESS, toggle="Y", ch=CHANNEL)
    d.cc(LOOP_BANK, "D", "TAP", CC_TAP, off=NO_SEND, ch=CHANNEL)

    names[FS_BANK] = ("FS", "switches")
    for btn, number, n in zip(("A", "B", "C", "D"), CC_FS, range(1, 5)):
        switch(d, FS_BANK, btn, f"FS{n}", number)
    switch(d, FS_BANK, "1", "DRUM", CC_DRUM_MENU)
    switch(d, FS_BANK, "2", "DRPL", CC_DRUM_PLAY)
    switch(d, FS_BANK, "3", "TUNR", CC_TUNER)
    # Lit while bypassed, the analog bypass
    d.cc(FS_BANK, "4", "BYP", CC_BYPASS, on="0", off="2", toggle="Y", ch=CHANNEL)

    full_range_pedals(d)
    d.exp.loc[1, "Out_Max"] = "100"     # Patch Volume goes up to 100
    return d, names


def main() -> int:
    d, names = build()
    return write_template(OUT, d, names, global_settings("Ampero II", CHANNEL, CC_EXP, CC_VOLUME),
                          "Hotone Ampero II template, generated by make_ampero_ii_template.py")


if __name__ == "__main__":
    sys.exit(main())
