#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the Apple MainStage template, python/templates/MainStage.csv.

Nothing to learn for the main controls: a Program Change selects the patch
with that number, and the rest are MainStage's own keyboard shortcuts, sent
by the pedal as a USB keyboard to the MainStage window in front. The FX
buttons send CCs to assign to screen controls with Assign & Map.

    python3 python/make_mainstage_template.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from lib.templateMaker import full_range_pedals, global_settings, write_template  # noqa: E402
from make_demo_config import Demo  # noqa: E402

OUT = os.path.join(HERE, "templates", "MainStage.csv")

CHANNEL = "1"
CTRL, CMD = "1", "8"    # the Key command's modifiers
# MainStage's shortcuts, in Perform mode
KEYS = (("1", "PAT-", "", "up"),        # the previous patch
        ("2", "PAT+", "", "down"),      # the next patch
        ("3", "SET-", "", "left"),      # the first patch of the previous set
        ("4", "SET+", "", "right"),     # the first patch of the next set
        ("A", "PLAY", "", "space"),     # play / stop
        ("B", "REC", CTRL, "r"),        # recording on / off
        ("C", "TUNR", CMD, "t"),        # show / hide the tuner
        ("D", "TAP", CTRL, "t"))        # tap tempo
CC_FX = ("20", "21", "22", "23")    # for Assign & Map: 127 on, 0 off
CC_EXP1 = "11"          # expression, and the modulation wheel
CC_EXP2 = "1"

PATCH_BANKS = 31        # banks 0-30 select patches 0-30
CTRL_BANK = 31


def build():
    d = Demo()
    names = {}

    for bank in range(PATCH_BANKS):
        names[bank] = (f"P{bank:03d}", "patch")
        d.on_enter(bank, CommandType="PC",
                   **{"Channel_(PC/CC/Note/PB)": CHANNEL, "Number_(PC/CC/Note)": str(bank)})
        for btn, label, mods, key in KEYS:
            d.key(bank, btn, label, mods, key)

    names[CTRL_BANK] = ("CTRL", "controls")
    d.key(CTRL_BANK, "1", "PANC", CTRL, "p")    # panic
    d.key(CTRL_BANK, "2", "MUTE", CTRL, "m")    # master mute
    d.key(CTRL_BANK, "3", "PAT-", "", "up")
    d.key(CTRL_BANK, "4", "PAT+", "", "down")
    for btn, number, n in zip(("A", "B", "C", "D"), CC_FX, range(1, 5)):
        d.cc(CTRL_BANK, btn, f"FX{n}", number, toggle="Y", ch=CHANNEL)

    full_range_pedals(d)
    return d, names


def main() -> int:
    d, names = build()
    return write_template(OUT, d, names, global_settings("MainStage", CHANNEL, CC_EXP1, CC_EXP2),
                          "Apple MainStage template, generated by make_mainstage_template.py")


if __name__ == "__main__":
    sys.exit(main())
