#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the Boss RC-600 template, python/templates/RC-600.csv.

Memories need nothing: a Program Change 0-98 recalls memory 01-99, and MIDI
Start and Stop start and stop every track. The rest has no MIDI CC out of
the box: the numbers below have to be set as ASSIGN sources in each memory
used (MEMORY > ASSIGN, see the CC_* constants and the manual), where the
RC-600 accepts CC 1-31 and 64-95.

    python3 python/make_rc600_template.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from lib.templateMaker import full_range_pedals, global_settings, write_template  # noqa: E402
from make_demo_config import Demo  # noqa: E402

OUT = os.path.join(HERE, "templates", "RC-600.csv")

CHANNEL = "1"           # the RC-600's RX CH CTL, MENU > MIDI

# ASSIGN sources: 127 on the press, 0 on the release, SOURCE MODE MOMENT
CC_REC_PLAY = ("80", "81", "82", "86", "87", "88")  # TRK1-6 REC/PLY
CC_UNDO = "83"          # CUR.TRK UN/RED
CC_CLEAR = "84"         # CUR.TRK CLEAR
CC_TAP = "85"           # TAP TEMPO
# The expression pedals, as ASSIGN sources too, for LOOP LEVEL or a
# track's level
CC_EXP1 = "70"
CC_EXP2 = "71"

MEMORY_BANKS = 31       # banks 0-30 recall memories 01-31
TRACKS_BANK = 31


def press(d, bank, btn, label, number):
    d.cc(bank, btn, label, number, ch=CHANNEL)


def common(d, bank):
    press(d, bank, "4", "UNDO", CC_UNDO)
    d.transport(bank, "A", "STRT", "Start")
    d.transport(bank, "B", "STOP", "Stop")
    press(d, bank, "C", "CLR", CC_CLEAR)
    press(d, bank, "D", "TAP", CC_TAP)


def build():
    d = Demo()
    names = {}

    for bank in range(MEMORY_BANKS):
        names[bank] = (f"M{bank + 1:03d}", "RC-600")
        d.on_enter(bank, CommandType="PC",
                   **{"Channel_(PC/CC/Note/PB)": CHANNEL, "Number_(PC/CC/Note)": str(bank)})
        for btn, number, n in zip(("1", "2", "3"), CC_REC_PLAY, (1, 2, 3)):
            press(d, bank, btn, f"TRK{n}", number)
        common(d, bank)

    names[TRACKS_BANK] = ("TRKS", "tracks")
    for btn, number, n in zip(("1", "2", "3"), CC_REC_PLAY[3:], (4, 5, 6)):
        press(d, TRACKS_BANK, btn, f"TRK{n}", number)
    common(d, TRACKS_BANK)

    full_range_pedals(d)
    return d, names


def main() -> int:
    d, names = build()
    return write_template(OUT, d, names, global_settings("RC-600", CHANNEL, CC_EXP1, CC_EXP2),
                          "Boss RC-600 template, generated by make_rc600_template.py")


if __name__ == "__main__":
    sys.exit(main())
