#! env python3
# -*- coding: utf-8 -*-
"""Generate the Cantabile template, python/templates/Cantabile.csv.

A Program Change loads the song of the set list with that program number,
once a binding in the background rack sends the pedal's Program Changes to
the set list; T and Shift+T are Cantabile's own shortcuts for the next and
previous state, sent by the pedal as a USB keyboard. Tap tempo, play / stop
and panic are CCs to bind once (see the CC_* constants and the manual); the
FX buttons, CCs for plugin parameters.

    python3 python/make_cantabile_template.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from lib.templateMaker import full_range_pedals, global_settings, write_template  # noqa: E402
from make_demo_config import Demo  # noqa: E402

OUT = os.path.join(HERE, "templates", "Cantabile.csv")

CHANNEL = "1"
SHIFT = "2"             # the Key command's modifier
# Bindings: 127 on the press, 0 on the release
CC_TAP = "20"           # tap tempo
CC_PLAY = "21"          # play / stop
CC_PANIC = "22"         # panic
CC_FX = ("24", "25", "26")      # for plugin parameters: 127 on, 0 off
CC_EXP1 = "11"
CC_EXP2 = "1"

SONG_BANKS = 32         # banks 0-31 load the songs with program 0-31


def build():
    d = Demo()
    names = {}

    for bank in range(SONG_BANKS):
        names[bank] = (f"S{bank:03d}", "song")
        d.on_enter(bank, CommandType="PC",
                   **{"Channel_(PC/CC/Note/PB)": CHANNEL, "Number_(PC/CC/Note)": str(bank)})
        d.key(bank, "1", "STA-", SHIFT, "t")    # the previous state
        d.key(bank, "2", "STA+", "", "t")       # the next state
        d.cc(bank, "3", "PLAY", CC_PLAY, ch=CHANNEL)
        d.cc(bank, "4", "PANC", CC_PANIC, ch=CHANNEL)
        for btn, number, n in zip(("A", "B", "C"), CC_FX, range(1, 4)):
            d.cc(bank, btn, f"FX{n}", number, toggle="Y", ch=CHANNEL)
        d.cc(bank, "D", "TAP", CC_TAP, ch=CHANNEL)

    full_range_pedals(d)
    return d, names


def main() -> int:
    d, names = build()
    return write_template(OUT, d, names, global_settings("Cantabile", CHANNEL, CC_EXP1, CC_EXP2),
                          "Cantabile template, generated by make_cantabile_template.py")


if __name__ == "__main__":
    sys.exit(main())
