#! env python3
# -*- coding: utf-8 -*-
"""Generate the Fractal Audio FM3 template, python/templates/FM3.csv.

The FM3 ships with no MIDI CC assigned, so the numbers below are the ones the
template sends and have to be assigned to the matching functions on the FM3,
under SETUP > MIDI/Remote (see the CC_* constants and the README). Preset
changes need nothing: they are plain Program Changes.

    python3 python/make_fm3_template.py
"""
import os
import sys

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from lib.configCsv import write_config_csv  # noqa: E402
from lib.configPacker import NUM_BANKS  # noqa: E402
from make_demo_config import Demo  # noqa: E402

OUT = os.path.join(HERE, "templates", "FM3.csv")

CHANNEL = "1"           # the FM3's MIDI channel, SETUP > MIDI/Remote > General

# SETUP > MIDI/Remote > Other
CC_TAP = "14"           # Tempo Tap
CC_TUNER = "15"         # Tuner
CC_SCENE = "34"         # Scene Select: value 0 = scene 1 ... 7 = scene 8
# SETUP > MIDI/Remote > External: the expression pedals, as External 1 and 2
CC_EXT1 = "16"
CC_EXT2 = "17"
# SETUP > MIDI/Remote > Looper
LOOPER = (("1", "REC", "20"), ("2", "PLAY", "21"), ("3", "UNDO", "22"), ("4", "ONCE", "23"),
          ("A", "REV", "24"), ("B", "HALF", "25"))
# SETUP > MIDI/Remote > Bypass: 64-127 engages the block, 0-63 bypasses it
BYPASS = (("1", "DRV", "Drive 1", "40"), ("2", "COMP", "Compressor 1", "41"),
          ("3", "PHAS", "Phaser 1", "42"), ("4", "CHOR", "Chorus 1", "43"),
          ("A", "DLY", "Delay 1", "44"), ("B", "REV", "Reverb 1", "45"),
          ("C", "WAH", "Wah 1", "46"), ("D", "PTCH", "Pitch 1", "47"))

PRESET_BANKS = 30       # banks 0-29 load presets 0-29
LOOP_BANK = 30
FX_BANK = 31
SCENE_BUTTONS = (("1", 1), ("2", 2), ("3", 3), ("4", 4), ("A", 5), ("B", 6))
NO_SEND = "128"         # an off value of 128 sends nothing


def tuner_and_tap(d, bank):
    # Tuner latches: in on one press, out on the next
    d.cc(bank, "C", "TUNR", CC_TUNER, toggle="Y", ch=CHANNEL)
    # Tap sends only on the press; a second message on the release would
    # count as another tap
    d.cc(bank, "D", "TAP", CC_TAP, off=NO_SEND, ch=CHANNEL)


def build():
    d = Demo()
    names = {}

    for bank in range(PRESET_BANKS):
        names[bank] = (f"P{bank:03d}", "FM3 prst")
        d.on_enter(bank, CommandType="PC",
                   **{"Channel_(PC/CC/Note/PB)": CHANNEL, "Number_(PC/CC/Note)": str(bank)})
        for btn, scene in SCENE_BUTTONS:
            # A toggle in an exclusive group, so the LED and the display cell
            # show the scene last picked; the off value sends nothing, so
            # switching a scene button off leaves the FM3 alone
            d.cc(bank, btn, f"SCN{scene}", CC_SCENE, on=str(scene - 1), off=NO_SEND,
                 toggle="Y", ch=CHANNEL)
            d.group(bank, btn, 1)
        tuner_and_tap(d, bank)

    names[LOOP_BANK] = ("LOOP", "looper")
    for btn, label, number in LOOPER:
        d.cc(LOOP_BANK, btn, label, number, off=NO_SEND, ch=CHANNEL)
    tuner_and_tap(d, LOOP_BANK)

    names[FX_BANK] = ("FX", "bypass")
    for btn, label, _, number in BYPASS:
        d.cc(FX_BANK, btn, label, number, toggle="Y", ch=CHANNEL)

    # The expression pedals, calibrated end points left at the full range
    d.exp.loc[0, ["Min_ADC", "Max_ADC", "Curve", "Invert", "Channel"]] = ["100", "3900", "Linear", "N", "Global"]
    d.exp.loc[1, ["Min_ADC", "Max_ADC", "Curve", "Invert", "Channel"]] = ["100", "3900", "Linear", "N", "Global"]
    return d, names


def global_settings() -> pd.DataFrame:
    return pd.DataFrame(
        [
            {"Label": l, "Value": v}
            for l, v in (
                ("MIDI_Channel", CHANNEL),
                ("ConfigName", "FM3"),
                ("Exp1_CC", CC_EXT1),
                ("Exp2_CC", CC_EXT2),
                ("Bank_Up_LED_Mode", "Normal"),
                ("Bank_Down_LED_Mode", "Normal"),
                ("RealTime_Passthrough", "N"),
                ("USB_MIDI_Thru", "N"),
                ("Remember_State", "N"),
                ("Long_Press_ms", "500"),
                ("LED_Brightness", "100"),
                ("LED_Rest_Brightness", "25"),
                ("Bank_Jump_Step", "10"),
                ("Bank_Switch_Mode", "Bank"),
            )
        ]
    )


def main() -> int:
    d, names = build()
    banks = pd.DataFrame(
        [
            {"Bank_Number": str(b), "Bank_Name_Large": names[b][0], "Bank_Info_Small": names[b][1]}
            for b in range(NUM_BANKS)
        ]
    )
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    write_config_csv(
        OUT,
        global_settings(),
        banks,
        d.buttons,
        note="Fractal Audio FM3 template, generated by make_fm3_template.py",
        df_long_press=d.long,
        df_double_press=d.double,
        df_bank_expression=d.bank_exp,
        df_expression=d.exp,
        df_bank_enter=d.enter,
        df_sysex=d.sysex,
        df_bank_switch=d.bank_switch_frame,
    )
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
