#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the Strymon Iridium template, python/templates/Iridium.csv.

The Iridium has a fixed MIDI map, "MIDI CC numbers" in its manual (rev D),
so nothing has to be assigned on it. It has no DIN socket: MIDI goes into
its EXP jack, set to Digital mode, through Strymon's MIDI EXP cable or any
TRS MIDI adapter.

    python3 python/make_iridium_template.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from lib.templateMaker import full_range_pedals, global_settings, write_template  # noqa: E402
from make_demo_config import Demo  # noqa: E402

OUT = os.path.join(HERE, "templates", "Iridium.csv")

CHANNEL = "1"           # the Iridium's MIDI channel, green for 1 by default

# The Iridium's MIDI map
CC_VOLUME = "7"         # Volume Pedal
CC_DRIVE = "13"
CC_ROOM_SIZE = "18"     # 1 small, 2 medium, 3 large
CC_AMP = "19"           # 1 round, 2 chime, 3 punch
CC_BYPASS = "102"       # 0 bypass, 1-127 on

PRESET_BANKS = 32       # banks 0-31 load presets 0-31; 0 is the one on FAV
AMPS = (("1", "RND", "1"), ("2", "CHIM", "2"), ("3", "PNCH", "3"))
ROOMS = (("A", "SMAL", "1"), ("B", "MED", "2"), ("C", "LRGE", "3"))
NO_SEND = "128"


def build():
    d = Demo()
    names = {}

    for bank in range(PRESET_BANKS):
        names[bank] = (f"P{bank:03d}", "Iridium")
        d.on_enter(bank, CommandType="PC",
                   **{"Channel_(PC/CC/Note/PB)": CHANNEL, "Number_(PC/CC/Note)": str(bank)})
        # Two exclusive groups, so the LEDs show the amp and the room last
        # picked; switching one off sends nothing
        for group, number, choices in ((1, CC_AMP, AMPS), (2, CC_ROOM_SIZE, ROOMS)):
            for btn, label, value in choices:
                d.cc(bank, btn, label, number, on=value, off=NO_SEND, toggle="Y", ch=CHANNEL)
                d.group(bank, btn, group)
        # Lit while bypassed: a preset loads on
        d.cc(bank, "D", "BYP", CC_BYPASS, on="0", off="127", toggle="Y", ch=CHANNEL)

    full_range_pedals(d)
    return d, names


def main() -> int:
    d, names = build()
    return write_template(OUT, d, names, global_settings("Iridium", CHANNEL, CC_VOLUME, CC_DRIVE),
                          "Strymon Iridium template, generated by make_iridium_template.py")


if __name__ == "__main__":
    sys.exit(main())
