#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the Gig Performer template, python/templates/Gig_Performer.csv.

A Program Change selects the rackspace with that number, as Gig Performer
numbers them out of the box, and the arrow keys and Shift+T are its own
shortcuts, sent by the pedal as a USB keyboard. Tap tempo, play / stop and
panic are CCs to learn once in Options > Global MIDI (see the CC_*
constants and the manual); the FX buttons, CCs for widgets.

    python3 python/make_gig_performer_template.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from lib.templateMaker import full_range_pedals, global_settings, write_template  # noqa: E402
from make_demo_config import Demo  # noqa: E402

OUT = os.path.join(HERE, "templates", "Gig_Performer.csv")

CHANNEL = "1"
SHIFT = "2"             # the Key command's modifier
# Options > Global MIDI, learnt with Momentary ticked: 127 on the press, 0
# on the release
CC_TAP = "20"           # Tap Tempo
CC_PLAY = "21"          # Play/Stop
CC_PANIC = "22"         # Panic
CC_FX = ("24", "25")  # for widgets: 127 on, 0 off
CC_EXP1 = "11"
CC_EXP2 = "1"

RACKSPACE_BANKS = 32    # banks 0-31 select rackspaces 0-31


def build():
    d = Demo()
    names = {}

    for bank in range(RACKSPACE_BANKS):
        names[bank] = (f"R{bank:03d}", "rackspc")
        d.on_enter(bank, CommandType="PC",
                   **{"Channel_(PC/CC/Note/PB)": CHANNEL, "Number_(PC/CC/Note)": str(bank)})
        # The song part above and below, in the Setlist view
        d.key(bank, "1", "PRT-", "", "up")
        d.key(bank, "2", "PRT+", "", "down")
        d.cc(bank, "3", "PLAY", CC_PLAY, ch=CHANNEL)
        d.cc(bank, "4", "PANC", CC_PANIC, ch=CHANNEL)
        d.cc(bank, "A", "FX1", CC_FX[0], toggle="Y", ch=CHANNEL)
        d.cc(bank, "B", "FX2", CC_FX[1], toggle="Y", ch=CHANNEL)
        d.key(bank, "C", "TUNR", SHIFT, "t")
        d.cc(bank, "D", "TAP", CC_TAP, ch=CHANNEL)

    full_range_pedals(d)
    return d, names


def main() -> int:
    d, names = build()
    return write_template(OUT, d, names, global_settings("Gig Performer", CHANNEL, CC_EXP1, CC_EXP2),
                          "Gig Performer template, generated by make_gig_performer_template.py")


if __name__ == "__main__":
    sys.exit(main())
