"""The committed CSVs are what their generators write.

python/demo-all-features.csv and python/templates/*.csv are generated by the
make_*.py scripts next to them. A generator changed without running it again
leaves a file behind it, which the configurator and the web page then offer.
Each generator is run into a temporary file and compared, byte for byte.

When this fails, run the generator named in the failure and commit its file.
"""
import contextlib
import importlib
import io
import os
import sys
import tempfile
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)

GENERATORS = {
    "make_demo_config": "demo-all-features.csv",
    "make_fm3_template": os.path.join("templates", "FM3.csv"),
    "make_hx_stomp_template": os.path.join("templates", "HX_Stomp.csv"),
    "make_kemper_player_template": os.path.join("templates", "Kemper_Player.csv"),
    "make_quad_cortex_template": os.path.join("templates", "Quad_Cortex.csv"),
    "make_h90_template": os.path.join("templates", "H90.csv"),
    "make_timeline_template": os.path.join("templates", "TimeLine.csv"),
    "make_bigsky_template": os.path.join("templates", "BigSky.csv"),
    "make_volante_template": os.path.join("templates", "Volante.csv"),
    "make_iridium_template": os.path.join("templates", "Iridium.csv"),
    "make_ampero_ii_template": os.path.join("templates", "Ampero_II.csv"),
    "make_rc600_template": os.path.join("templates", "RC-600.csv"),
    "make_mainstage_template": os.path.join("templates", "MainStage.csv"),
    "make_gig_performer_template": os.path.join("templates", "Gig_Performer.csv"),
    "make_cantabile_template": os.path.join("templates", "Cantabile.csv"),
    "make_ableton_live_template": os.path.join("templates", "Ableton_Live.csv"),
    "make_enzo_x_template": os.path.join("templates", "Enzo_X.csv"),
    "make_lvx_template": os.path.join("templates", "LVX.csv"),
    "make_mercuryx_template": os.path.join("templates", "MercuryX.csv"),
}


def read(path):
    with open(path, "rb") as f:
        return f.read()


class GeneratorsTest(unittest.TestCase):
    def test_every_template_has_its_generator(self):
        templates = sorted(os.path.join("templates", n)
                           for n in os.listdir(os.path.join(ROOT, "templates")) if n.endswith(".csv"))
        self.assertEqual(templates, sorted(p for p in GENERATORS.values() if p.startswith("templates")))

    def test_committed_file_is_what_the_generator_writes(self):
        for name, path in GENERATORS.items():
            with self.subTest(name):
                module = importlib.import_module(name)
                self.assertEqual(os.path.abspath(module.OUT), os.path.join(ROOT, path))
                with tempfile.TemporaryDirectory() as tmp:
                    out = os.path.join(tmp, os.path.basename(path))
                    saved, module.OUT = module.OUT, out
                    try:
                        with contextlib.redirect_stdout(io.StringIO()):
                            self.assertEqual(module.main(), 0)
                    finally:
                        module.OUT = saved
                    self.assertTrue(read(out) == read(os.path.join(ROOT, path)),
                                    f"{path} is not what {name}.py writes: run python/{name}.py")


if __name__ == "__main__":
    unittest.main()
